apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: eowusur7l-go 
  janus-idp.io/tekton: eowusur7l-go
  backstage.io/kubernetes-id: eowusur7l-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eowusur7l-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml